version: '3.8'
services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    image:
      app-python-flask
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://postgres:12345678@db:5432/Inventario
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: Inventario
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: